version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t duobtms/frontend .
      - docker tag duobtms/frontend:latest 617624234305.dkr.ecr.eu-central-1.amazonaws.com/duobtms/frontend:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 617624234305.dkr.ecr.eu-central-1.amazonaws.com
      - echo Pushing the Docker images...
      - docker push 617624234305.dkr.ecr.eu-central-1.amazonaws.com/duobtms/frontend:latest
      - echo Writing image definitions file...
      - printf '[{"name":"DuobTMSWeb", "imageUri":"%s"}]' docker push 617624234305.dkr.ecr.eu-central-1.amazonaws.com/duobtms/frontend:latest > imagedefinitionsFront.json
artifacts:
  files: imagedefinitionsFront.json