version: '3.8'
services:
  duob-tms-service:
    image: 127.0.0.1:5000/duob-tms-service
    environment:
      - SPRING_PROFILES_ACTIVE=${profile}
    ports:
      - 8085:8080
    #    volumes:
    #      - type: bind
    #        source: /home/duob-tms/documents/
    #        target: /documents/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  duob-tms-web:
    image: 127.0.0.1:5000/duob-tms-web
    depends_on:
      - duob-tms-service
    ports:
      - 9999:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
